### ISSUE TITLE
SLIC output incompatible with current lcsim impl of LCIO

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#30]
Hi, Jeremy

Ok, thanks a lot for fixing it. Currently I do not use the crossing angle. But please fix this feature.

 The next step is to run LCSIM on the output from this SLIC version. The vesion lcism (trunk, 3.9)  fails with this error. This can be some slic feature, or the trunk version of LCSIM:

Error from LCSIM:

```
Apr 20, 2017 9:24:49 PM org.lcsim.job.JobControlManager run
INFO: running job
Apr 20, 2017 9:24:49 PM org.lcsim.job.JobControlManager run
INFO: Job started: Thu Apr 20 21:24:49 CDT 2017
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.Vector.grow(Vector.java:266)
	at java.util.Vector.ensureCapacityHelper(Vector.java:246)
	at java.util.Vector.setSize(Vector.java:289)
	at hep.io.sio.SIOInputStream.readPTag(SIOInputStream.java:43)
	at org.lcsim.lcio.SIOSimTrackerHit.<init>(SIOSimTrackerHit.java:67)
	at org.lcsim.lcio.SIOSimTrackerHitBlockHandler.addCollectionElements(SIOSimTrackerHitBlockHandler.java:31)
	at org.lcsim.lcio.AbstractBlockHandler.readCollection(AbstractBlockHandler.java:39)
	at org.lcsim.lcio.AbstractBlockHandler.readBlock(AbstractBlockHandler.java:32)
	at org.lcsim.lcio.LCIOReader.read(LCIOReader.java:77)
	at org.lcsim.util.loop.LCIOEventSource.next(LCIOEventSource.java:129)
	at org.freehep.record.loop.DefaultRecordLoop.fetchRecord(DefaultRecordLoop.java:809)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:648)
	at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
	at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
	at org.lcsim.job.JobControlManager.run(JobControlManager.java:962)
	at org.lcsim.job.JobControlManager.main(JobControlManager.java:174)
Apr 20, 2017 9:24:52 PM org.lcsim.job.JobControlManager run
SEVERE: A fatal error occurred when running the job.
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at org.lcsim.util.loop.LCSimLoop.handleSourceError(LCSimLoop.java:202)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:655)
	at org.freehep.record.loop.DefaultRecordLoop.execute(DefaultRecordLoop.java:566)
	at org.lcsim.util.loop.LCSimLoop.loop(LCSimLoop.java:152)
	at org.lcsim.job.JobControlManager.run(JobControlManager.java:962)
	at org.lcsim.job.JobControlManager.main(JobControlManager.java:174)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.Vector.grow(Vector.java:266)
	at java.util.Vector.ensureCapacityHelper(Vector.java:246)
	at java.util.Vector.setSize(Vector.java:289)
	at hep.io.sio.SIOInputStream.readPTag(SIOInputStream.java:43)
	at org.lcsim.lcio.SIOSimTrackerHit.<init>(SIOSimTrackerHit.java:67)
	at org.lcsim.lcio.SIOSimTrackerHitBlockHandler.addCollectionElements(SIOSimTrackerHitBlockHandler.java:31)
	at org.lcsim.lcio.AbstractBlockHandler.readCollection(AbstractBlockHandler.java:39)
	at org.lcsim.lcio.AbstractBlockHandler.readBlock(AbstractBlockHandler.java:32)
	at org.lcsim.lcio.LCIOReader.read(LCIOReader.java:77)
	at org.lcsim.util.loop.LCIOEventSource.next(LCIOEventSource.java:129)
	at org.freehep.record.loop.DefaultRecordLoop.fetchRecord(DefaultRecordLoop.java:809)
	at org.freehep.record.loop.DefaultRecordLoop.loop(DefaultRecordLoop.java:648)
	... 4 more
```

**Comment by JeremyMcCormick** [comment]
Okay, thanks for the information....

Maybe for now need to backup to LCIO v02-06 as I think lcsim is not up to date with v02-07.

**Comment by JeremyMcCormick** [comment]
Use LCIO v02-07-04 and lcsim should be able to read the output fine.
