### ISSUE TITLE
Seg fault on program exit

### ISSUE THREAD

**Issue by JeremyMcCormick** [slaclab/slic#55]
This looks like a double deletion issue:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000460932 in slic::RunManager::~RunManager() ()
(gdb) bt
#0  0x0000000000460932 in slic::RunManager::~RunManager() ()
#1  0x0000000000461e6d in slic::SlicApplication::~SlicApplication() ()
#2  0x0000000000462439 in slic::SlicApplication::~SlicApplication() ()
#3  0x000000000046524e in slic::SlicMain::main(int, char**) ()
#4  0x0000003f4381ed1d in __libc_start_main () from /lib64/libc.so.6
#5  0x0000000000421e55 in _start ()
(gdb)
```

**Comment by JeremyMcCormick** [comment]
The #56 PR should fix this for now (don't think it is necessary to delete the run manager at all).
